# http://docs.travis-ci.com/user/languages/go/
language: go
os:
  - linux
  - osx
go:
  - 1.5
install: true
script: script/cibuild
notifications:
  email: false
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update          ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git     ; fi
  - repo=`basename $PWD`; localDir=`dirname $PWD`; cfDir="`dirname $localDir`/github"
  - if [[ "$localDir" != "$cfDir" ]]; then mv "$localDir" "$cfDir"; cd ../../github/$repo; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$repo; fi
  - export GIT_LFS_TEST_DIR="$localDir/git-lfs-tests"
